services:
  portfolio-app:
    build: .
    container_name: portfolio_nghiapd
    restart: unless-stopped
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=3000
